service: nodeless

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: sa-east-1
  memorySize: 256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      resource:
        - arn:aws:s3:::*

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
          cors: true
          credentials: true
          response:
            statusCodes:
              200:
                template: 'Hello {{input.params.name}}!'

  optimize:
    handler: optimize.handler
    environment:
      bucket: serverless
    events:
      - s3:
          bucket: serverless
          events: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .png

  firebaseAuth:
    handler: handler.firebaseAuth
    events:
      - http:
          path: /firebase-auth
          method: post
          cors: true
          credentials: true
          response:
            statusCodes:
              200:
                template: 'Hello {{input.params.name}}!'


plugins:
  - "serverless-offline"